site_name: TransformersSharp

nav:
  - Introduction: index.md
  - Tokenizers: tokenizers.md
  - Embeddings (Sentence Transformers): sentence_transformers.md
  - Pipelines:
    - Introduction: pipelines/index.md
    - Text Classification: pipelines/text_classification.md
    - Text Generation: pipelines/text_generation.md
    - Image Classification: pipelines/image_classification.md
    - Object Detection: pipelines/object_detection.md
    - Text to Audio: pipelines/text_to_audio.md
    - Automatic Speech Recognition: pipelines/auto_speech_recognition.md

plugins:
  - glightbox
  - include-markdown

theme:
  name: material
  logo: media/logo.png
  # favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Fira Mono #Monospaced
    text: Montserrat #Regular
  palette:
    - scheme: default  # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

repo_url: https://github.com/tonybaloney/TransformersSharp
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
